export const ROUTES = {
  dashboard: "dashboard",
  category: "/category",
  comment: "/comment",
  commentView: "/commentView",
  order: "/order",
  orderDetail: "/orderDetail",
  orderView: "/orderView",
  productList: "/productList",
  productView: "/productView",
  productUpdate: "/productUpdate",
  productCreate: "/productCreate",
  profile: "/profile",
  home: "/",
  login: "/login",
  signup: "/signup",
  shop: "/shop",
  cart: "/cart",
  checkout: "/checkout",
  services: "/services",
  contact: "/contact",
  about: "/about",
};
